- name: print number
  hosts: localhost
  vars:
    number: 6
  become: yes
  tasks:
  - name: less or greater
    ansible.builtin.debug:
      msg: "{{ number }} is less than 10"
    when: number|int < 10
