- name: datatypes
  hosts: localhost
  become: yes
  vars:
    course: devops
    experiance:
      devops: 3
      aws: 2
      linux: 2
    tools:
    - aws
    - devops
    - linux
    ecrtification: yes
  tasks:
  - name: print info
    ansible.builtin.debug:
      msg: "{{ course }},{{ experiance }}, {{ tools }},{{ ecrtification }}"