- name: convert dict to item
  hosts: localhost
  become: yes
  vars:
    dict:
      devop: 2
      linux: 2
      aws: 1
  tasks:
  - name: dict to item
    ansible.builtin.debug:
      msg: "{{ dict | dict2items }}"

- name: item 2 dict
  hosts: localhost
  become: yes
  vars:
    tags:
    - aws
    - dev
    - linux
  tasks:
  - name: convert item2dict
    ansible.builtin.debug:
      msg: "{{ tags | items2dict }}"