- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: start and enable
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: remove html
  ansible.builtin.file:
    name: "{{ path }}"
    state: absent

- name: create new emty html
  ansible.builtin.file:
    name: "{{ path }}"
    state: directory

- name: download url
  ansible.builtin.unarchive:
    src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: "{{ path }}"

- name: editthe file
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf
    notify:
    - restrart nginx